// <auto-generated />
namespace AllSports.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class StoryClass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StoryClass));
        
        string IMigrationMetadata.Id
        {
            get { return "202009011407457_StoryClass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
